# fly.toml app configuration file generated for bonds-api on 2025-08-03T20:39:59+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bonds-api'
primary_region = 'waw'

[build]

[http_service]
  internal_port = 5150
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
