set windows-shell := ["pwsh.exe", "-c"]

gen-api:
    npx --yes @openapitools/openapi-generator-cli@2.21.4 generate -g rust-axum -i .\openapi.yaml --enable-post-process-file -o crates/api --additional-properties generateAliasAsModel=true
    
lgtm:
    docker run -p 3000:3000 -p 4317:4317 -p 4318:4318 --rm -ti grafana/otel-lgtm
    
fmt:
    cargo fmt
    
fmt-clippy:
    cargo clippy --tests --all-features --fix --allow-dirty --allow-staged
    just fmt