openapi: 3.0.0
info:
  title: Bonds API
  version: 0.0.1

servers:
  - # noinspection HttpUrlsUsage
    url: http://localhost:5150
    description: Local server for development

paths:
  /bonds:
    get:
      operationId: getBonds
      summary: Returns a list of bonds.
      responses:
        "200":
          description: A JSON array of bond names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string