[package]
name = "bonds-reader"
version.workspace = true
edition.workspace = true

[dependencies]
calamine.workspace = true
anyhow.workspace = true
chrono.workspace = true
model.workspace = true
rust_decimal.workspace = true

[dev-dependencies]
insta.workspace = true