name: Scraper Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2022, macos-13]
        python-version: ['3.13']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: 'scraper/requirements.txt'

    - name: Install system dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y ghostscript

    - name: Install system dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install ghostscript
        sudo ln -sf /usr/lib/libgs.so $(brew --prefix)/lib/libgs.dylib

    - name: Install system dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install ghostscript

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scraper/requirements.txt

    - name: Run tests
      run: |
        cd scraper
        python -m unittest discover -s tests -p "test_*.py" -v

    - name: Run tests with coverage (Ubuntu only)
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
      run: |
        cd scraper
        pip install coverage
        coverage run -m unittest discover -s tests -p "test_*.py"
        coverage report -m
        coverage xml

    - name: Upload coverage to Codecov (Ubuntu only)
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
      uses: codecov/codecov-action@v4
      with:
        file: ./scraper/coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
